#third document in python generaring a conflit error (error resolved)
print('login')
print('login')

print('login')
print('login')

print('login')
print('login')

print('login')

